server:
  port: 8080
  servlet-path: /system

management.security.enabled: false

cxf:
  path: /services/
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics
